import glob
import os

samples = ["SRR8134484", "SRR8134485"]

input_path = "/scratch/lustre/home/skba0280/Epigenomics_raw_data"

genome_index_dir = "/scratch/lustre/home/skba0280/references/human_genome/human_genome"

rule all:
   input:
      expand("results/fraction/{sample}.fastq",sample=samples),
      expand("results/fastp/{sample}_trimmed.fastq",sample=samples),
      expand("results/fastp/{sample}_fastp.html",sample=samples),
      expand("results/fastp/{sample}_fastp.json",sample=samples),
      expand("results/fastqc/{sample}_fastqc.html",sample=samples),
      expand("results/fastqc/{sample}_fastqc.zip",sample=samples),
      expand("results/fastqc/{sample}_trimmed_fastqc.html",sample=samples),
      expand("results/fastqc/{sample}_trimmed_fastqc.zip",sample=samples),
      expand("results/bwa/{sample}.sam",sample=samples),
      expand("results/bwa/{sample}.bam",sample=samples),
      expand("results/bwa/{sample}_rmdup.bam",sample=samples),
      "results/tagDirectory/tagInfo.txt",

rule fraction:
   input:
      fq = lambda wildcards:f"{input_path}/{wildcards.sample}.fastq.gz",
   output:
      fqfrac = "results/fraction/{sample}.fastq",
   shell:
      """
      seqtk sample -s100 {input.fq} 20000 > {output.fqfrac}
      """

rule fastp:
   input:
      fq = "results/fraction/{sample}.fastq",
   output:
      trimmed = "results/fastp/{sample}_trimmed.fastq",
      html = "results/fastp/{sample}_fastp.html",
      json = "results/fastp/{sample}_fastp.json",
   conda:"envs/preprocess_chipseq.yaml"
   shell:
      """
      fastp -i {input.fq} \
      -q 25 -l 20 \
      -o {output.trimmed} \
      -h {output.html} \
      -j {output.json}
      """

rule fastqc:
   input:
      fq = "results/fraction/{sample}.fastq",
      fq_trim = "results/fastp/{sample}_trimmed.fastq",
   output:
      html = "results/fastqc/{sample}_fastqc.html",
      zip = "results/fastqc/{sample}_fastqc.zip",
      html_trim = "results/fastqc/{sample}_trimmed_fastqc.html",
      zip_trim = "results/fastqc/{sample}_trimmed_fastqc.zip",
   conda:"envs/preprocess_chipseq.yaml"
   shell:
      """
      fastqc --outdir results/fastqc {input.fq} {input.fq_trim}
      """

rule bwa:
   input:
     fq = "results/fraction/{sample}.fastq",
   output:
     sam = "results/bwa/{sample}.sam",
     bam = "results/bwa/{sample}.bam",
     bam_rmdup = "results/bwa/{sample}_rmdup.bam",
   shell:
     """
     bwa mem -M {genome_index_dir} {input.fq} > {output.sam}
     samtools view -F 0x04 -q 30 -b {output.sam} | samtools sort -o {output.bam}
     samtools markdup -r -s {output.bam} {output.bam_rmdup}
     samtools index {output.bam_rmdup}
     """

rule makeTagDirectory:
   input:
     expand("results/bwa/{sample}_rmdup.bam",sample=samples),
   output:
     "results/tagDirectory/tagInfo.txt",
   shell:
     """
     makeTagDirectory results/tagDirectory {input}
     """
